---
apache_packages: [ 'apache2', 'apache2-utils', 'software-properties-common' ]

php_packages:
  - php
  - libapache2-mod-php
  - php-cli
  - php-fpm
  - php-json
  - php-pdo
  - php-mysql
  - php-zip
  - php-gd
  - php-mbstring
  - php-curl
  - php-xml
  - php-pear
  - php-bcmath
