---
- hosts: openjournal
  become: true
  gather_facts: false

  roles:
    - { role: mariadb, tags: [ 'mariadb' ] }
    - { role: apache2, tags: [ 'apache2' ] }
    - { role: openjournal, tags: [ 'openjournal' ] }
