---
apache_packages: [ 'apache2', 'apache2-utils', 'software-properties-common' ]

php_5_packages:
  - php5.6
  - libapache2-mod-php5.6
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-imap
  - php5.6-json
  - php5.6-mbstring
  - php5.6-mcrypt
  - php5.6-mysql
  - php5.6-opcache
  - php5.6-readline
  - php5.6-sqlite3
  - php5.6-xml

