---
- name: Activa php7.4
  community.general.apache2_module:
    name: php7.4
    state: present
  listen: servicios_apache
  
- name: Recargar Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
  listen: servicios_apache

- name: Reiniciar Apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  listen: servicios_apache


