---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instala Apache
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ apache_packages }}"

- name: Agregar PPA para php_5.6
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Instala módulos PHP
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ php_5_packages }}"

- name: Creando directorio para subida de archivos
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755
  with_items: [ '/var/www/files', '/var/www/html/openjournal' ]

- name: Descarga y descomprime openjournal
  ansible.builtin.unarchive:
    src: "{{ ojs_2x_url }}"
    dest: /var/www/html/openjournal
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755
    remote_src: true
    extra_opts: --strip-components=1
  notify: servicios_apache


